### ISSUE TITLE
Relax dask-core upper bound

### ISSUE THREAD

**Issue by scottyhq** [gjoseph92/geogif#13]
Since dask is using calver I think it's safe to remove the upper bound here 
https://github.com/gjoseph92/geogif/blob/6fc66faebf5c6ed3d5e6fdcb1213e2ca3645e0fc/pyproject.toml#L12

Ran into this trying to keep geogif in an environment with newer dask versions
https://github.com/pangeo-data/pangeo-docker-images/pull/431#issuecomment-1416483271

Happy to submit the PR to fix @gjoseph92

**Comment by gjoseph92** [comment]
Please do so, thanks for noticing @scottyhq

**Comment by gjoseph92** [comment]
@scottyhq 0.1.4 is pushed to PyPI with your change
