### ISSUE TITLE
Adjust size of timestamp and/or dynamically scale according to output size

### ISSUE THREAD

**Issue by maawoo** [gjoseph92/geogif#18]
Hi there!
Love this project 🙂  I'm creating a bunch of animations from Sentinel-1 and -2 time-series for different study sites in South Africa right now. I have noticed that the timestamp ends up being too small when the AOI is big. Here is an [example GIF](https://upload.uni-jena.de/data/63fa0fa2f0a139.43717318/Kakamas_s2_ndvi_2W_fast.gif) (Link is valid until 6 months from now). 

It would be great to have more control of the timestamp size or if it would dynamically scale according to the size of the generated GIF.

**Comment by gjoseph92** [comment]
Hey @maawoo, just so you know, @ZachHoppinen got around to finally making the timestamp text resizable in #22. This feature is available now in `geogif=0.2`. Thanks for bringing this up, and sorry it took so long to resolve!
