### ISSUE TITLE
getsize is deprecated and should be removed

### ISSUE THREAD

**Issue by yutik-nn** [gjoseph92/geogif#19]
I am trying to run 

`geogif.gif(alt_ds.sla).compute()`

So make a gif of an Xarray dataset locally but get the following error: 
`RuntimeError: getsize is deprecated and should be removed.`

Why might that be?

**Comment by gjoseph92** [comment]
Thanks for reporting @yutik-nn. Looks like this method was removed in newer versions of Pillow.

`geogif=0.1.5` has just been released fixing this issue.
