### ISSUE TITLE
please remove python version limit

### ISSUE THREAD

**Issue by espiritocz** [gjoseph92/geogif#8]
hi,

looks like great tool!
I tried to install it using pip, but got error:
ERROR: Package 'geogif-0.1.2' requires a different Python: 3.7.6 not in '>=3.8,<4.0'

could you please remove the strict dependency on python 3.7.6 ?

thank you

**Comment by gjoseph92** [comment]
@espiritocz geogif requires Python 3.8 or later, which is what that error is telling you. Looks like you're using Python 3.7.6.
